org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.0
neo_version_range=[21.1,21.2)
loader_version_range=[4,)

# Mod Properties
mod_id=gearforge
mod_name=GearForge
mod_license=Apache-2.0
mod_version=1.0.0
mod_group_id=com.rater193.gearforge
mod_authors=rater193
mod_description=A Minecraft mod for creating custom gear and tools
